spring.application.name=JPAThymeleafProject

server.port=8095

spring.datasource.url=jdbc:oracle:thin:@project-db-campus.smhrd.com:1524:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=navercloudtest
spring.datasource.password=navercloudtest

server.servlet.context-path=/jpa

# jpa 설정
# 어떤 sql문법을 사용해야 하는지 작성
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 2. 구현된 sql구문을 콘솔에 출력
spring.jpa.show-sql=true
# 3. 콘솔에 출력시 줄바꿈
spring.jpa.properties.hibernate.format_sql=true
# 4. DDL 작동 여부
# create : 테이블을 서버가 실행될 때 마다 다시 생성. Drop - Create
# update : 테이블의 변경사항 Alter
spring.jpa.hibernate.ddl-auto=update